version: '3.5'

services: 

    backend:
        build: ../project/.
        ports: 
            - "8080:8080"
        networks:
            - employee-db
        depends_on: 
            - db
        links: 
            - db

    auth:
        build: ../auth-ms/.
        ports: 
            - "7050:7050"
        networks:
            - employee-db
        depends_on: 
            - db
        links: 
            - db

    db:
        image: postgres:9.4        
        ports:
            - "5432:5432"
        networks:
            - employee-db        
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: project
        volumes:
            - ../db/pgdata:/var/lib/postgresql/data
networks:
  employee-db: 